datakaveri/dx-resource-server

- src/main/java/iudx/resource/server/database/DatabaseVerticle.java
- src/main/java/iudx/resource/server/database/QueryDecoder.java
- src/test/java/iudx/resource/server/database/DatabaseServiceTest.java
* Supports ISO 8601 time formats for database query
* Added new test cases
* Minor fixes
> Fixed date validation

- configs/config-depl.json
- configs/config-dev.json
- configs/config-example.json
- configs/config-test.json
- docker-compose.yml
- pom.xml
- src/main/java/iudx/resource/server/apiserver/Validator.java
- src/main/java/iudx/resource/server/apiserver/query/NGSILDQueryParams.java
- src/main/java/iudx/resource/server/apiserver/validation/types/DateTypeValidator.java
- src/main/java/iudx/resource/server/authenticator/AuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/database/Constants.java
- src/main/java/iudx/resource/server/database/DatabaseService.java
- src/main/java/iudx/resource/server/database/DatabaseServiceImpl.java
- src/main/java/iudx/resource/server/database/DatabaseVerticle.java
- src/main/java/iudx/resource/server/database/QueryDecoder.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/resources/log4j2.xml
- src/test/java/iudx/resource/server/database/DatabaseServiceTest.java
The patch does following:
- configure the log level at docker-compose file using env variable.
- logging only to console in [logfmt ](https://brandur.org/logfmt) format.
- Comment all system.out statements.
- changing vertx to log4j log
> Configurable logging level, logfmt, comment sys.out.

- src/main/java/iudx/resource/server/apiserver/validation/types/QTypeValidator.java
Float value check is commented in Filterr query.
> commented <<q>> query float value check.

- configs/config-depl.json
- configs/config-dev.json
- docker-compose-production.yml
- docker-compose.yml
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/authenticator/AuthenticationVerticle.java
- src/main/java/iudx/resource/server/callback/CallbackVerticle.java
- src/main/java/iudx/resource/server/database/DatabaseVerticle.java
- src/main/java/iudx/resource/server/databroker/DataBrokerVerticle.java
- src/main/java/iudx/resource/server/deploy/Deployer.java
- src/main/resources/log4j2.xml
1.) Fix: temporal values are not allowed in /entities 
2.) default values to env variables in log4j2.xml
> FIX: error 400 for temporal params in /entities query.

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/Validator.java
- src/main/java/iudx/resource/server/apiserver/query/QueryMapper.java
- src/main/java/iudx/resource/server/apiserver/response/ResponseType.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/validation/ValidationFailureHandler.java
- src/main/java/iudx/resource/server/apiserver/validation/types/OptionsTypeValidator.java
- src/main/resources/post_request_schema.json
1. Date in post queries.
2. uniform response for 400
> Fixes for STQC suggestions

- configs/config-test.json
- pom.xml
- src/main/java/iudx/resource/server/apiserver/Validator.java
- src/main/java/iudx/resource/server/apiserver/query/QueryMapper.java
- src/main/java/iudx/resource/server/apiserver/validation/types/AttrsTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/CoordinatesTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/DateTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/DistanceTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/GeoRelTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/GeometryTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/IDTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/OptionsTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/QTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/TimeRelTypeValidator.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/resources/post_request_schema.json
- src/test/java/iudx/resource/server/apiserver/ValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/query/QueryMapperTest.java
- src/test/java/iudx/resource/server/apiserver/validation/AttrsTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/CoordinatesTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/DateTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/DistanceTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/GeoPropertyTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/GeoRelTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/GeometryTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/IdTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/OptionsTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/QTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/TimeRelTypeValidatorTest.java
- src/test/java/iudx/resource/server/databroker/AdapterEntitiesTest.java
This  PR covers : 
- Junit test case fixes / more coverage (Validation test cases)
- STQC fixes (partial)
- ZAP testing fixes (partial)
> junit ,stqc and zap testing fixes

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/handlers/ValidationHandler.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/util/HttpStatusCode.java
- src/main/java/iudx/resource/server/apiserver/util/RequestType.java
- src/main/java/iudx/resource/server/apiserver/util/Util.java
- src/main/java/iudx/resource/server/apiserver/validation/ValidatorsHandlersFactory.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/resources/post_entities_schema.json
- src/main/resources/post_temporal_schema.json
- src/test/resources/IUDX-Resource-Server-Release-v3.0.20210621.postman_collection.json
This PR include
1. complex post /entities PI
2. handling for 404,504 error cases thrown by vertx router.
> Feature : complex post /entities API

- docs/openapi.yaml
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/validation/HTTPRequestValidatiorsHandlersFactory.java
- src/main/java/iudx/resource/server/apiserver/validation/types/HeaderTokenValidation.java
changes : 
- Header length [Validation fix].
- Latest entity id length [validation fix].
- API specs [maxDistance(changed to 1..1000 from 0..1000, since maxDistance=0 make no sense & Results type changed to 'array')
> stqc round 2 fix

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/handlers/ValidationHandler.java
- src/main/java/iudx/resource/server/apiserver/service/CatalogueService.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/util/RequestType.java
- src/main/java/iudx/resource/server/apiserver/util/Util.java
- src/main/java/iudx/resource/server/apiserver/validation/ValidatorsHandlersFactory.java
- src/main/java/iudx/resource/server/apiserver/validation/types/OptionsHeaderValidator.java
- src/main/java/iudx/resource/server/authenticator/AuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/java/iudx/resource/server/databroker/util/Util.java
- src/test/java/iudx/resource/server/databroker/AdapterEntitiesTest.java
- src/test/resources/IUDX-Resource-Server-Release-v3.0.20210706.postman_collection.json
- src/test/resources/IUDX-Resource-Server-Release-v3.0.20210712.postman_collection.json
This PR include : 
- new /ingestion endpoint [ /iudx/v1/adapter endpoint is replaced with /ngsi-ld/v1/ingestion]
- only "**streaming**" is allowed in subscriptions API
> /Ingestion endpoint in resource server

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/handlers/ValidationHandler.java
- src/main/java/iudx/resource/server/apiserver/service/CatalogueService.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/util/RequestType.java
- src/main/java/iudx/resource/server/apiserver/util/Util.java
- src/main/java/iudx/resource/server/apiserver/validation/ValidatorsHandlersFactory.java
- src/main/java/iudx/resource/server/apiserver/validation/types/IDTypeValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/OptionsHeaderValidator.java
- src/main/java/iudx/resource/server/apiserver/validation/types/StringTypeValidator.java
- src/main/java/iudx/resource/server/authenticator/AuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/java/iudx/resource/server/databroker/util/Util.java
- src/test/java/iudx/resource/server/apiserver/ApiServerVerticleTest.java
- src/test/java/iudx/resource/server/databroker/AdapterEntitiesTest.java
- src/test/resources/IUDX-Resource-Server-Release-v3.0.20210712.postman_collection.json
- consecutive '**///**' are combined to single '**/'** 
- regex based validation for each component of id
> [Fix] id as path parameter

- docs/openapi.yaml
API specs change for new API and modified API endpoints.
> api specs changes

- pom.xml
- src/main/java/iudx/resource/server/apiserver/query/QueryMapper.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/QueryBuilder.java
- src/test/java/iudx/resource/server/apiserver/ValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/query/QueryMapperTest.java
- src/test/java/iudx/resource/server/database/DatabaseServiceTest.java
- src/test/java/iudx/resource/server/databroker/AdapterEntitiesTest.java
- src/test/java/iudx/resource/server/databroker/CallbackSubscriptionTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceTest.java
- src/test/java/iudx/resource/server/metering/MeteringServiceTest.java
[Coverage.Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/7497315/Coverage.Report.pdf)
Coverage percentage increased for Metering Verticle only.
> Metering coverage

- configs/config-depl.json
- configs/config-dev.json
- configs/config-example.json
- configs/config-test.json
- src/main/java/iudx/resource/server/authenticator/AuthenticationVerticle.java
- Please make the jwtIgnoreExpiry , a configurable option. It can be set to true in dev but in prod it can ignored or set to false.
> Add jwtIgnoreExpiry option in config

- src/main/java/iudx/resource/server/apiserver/service/CatalogueService.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/databroker/SubscriptionService.java
Resolves issue #160  and issue #161
> issue #160, #161 and #162

- .github/workflows/build.yml
- src/main/java/iudx/resource/server/database/archives/elastic/AttributeQueryParser.java
- src/main/java/iudx/resource/server/database/archives/elastic/exception/ESQueryDecodeException.java
- resolves compilation bug,
- use workflow to early catch compilation errors.
> compilation bug/ workflow

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/main/java/iudx/resource/server/metering/util/QueryBuilder.java
- src/test/java/iudx/resource/server/database/latest/LatestServiceTest.java
- src/test/java/iudx/resource/server/metering/MeteringServiceTest.java
[Newman Summary Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/7684511/Newman.Summary.Report.pdf)
[Surefire Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/7684512/Surefire.Report.pdf)
> Provider Api.

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/management/ManagementApi.java
- src/main/java/iudx/resource/server/apiserver/management/ManagementApiImpl.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/common/Response.java
- src/main/java/iudx/resource/server/database/postgres/PostgresServiceImpl.java
- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/java/iudx/resource/server/databroker/SubscriptionService.java
- src/main/java/iudx/resource/server/databroker/util/PermissionOpType.java
- src/main/java/iudx/resource/server/databroker/util/Util.java
User permission changes.
- User permissions(read/write) are created whenever a user creates an adapter or creates/updates a subscription.
- User permissions(read/write) are deleted whenever an adapter or subscription is deleted.
> Bug/1.17 ingestion & sub API

- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/validation/ValidatorsHandlersFactory.java
- src/main/resources/post_entities_schema.json
- src/main/resources/post_temporal_schema.json
> pagination only through request parameters

- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/test/java/iudx/resource/server/apiserver/validation/PaginationLimitTypeValidatorTest.java
[surefire-report.pdf](https://github.com/datakaveri/iudx-resource-server/files/7821547/surefire-report.pdf)
[newman-report.pdf](https://github.com/datakaveri/iudx-resource-server/files/7821548/IUDX-Resource-Server-Consumer-APIs-V3.5-2022-01-06-10-59-58-121-0.pdf)
--------------------------------------------------
also changed pagination test parameters (7500 and 10000)
> Reset password response

- Jenkinsfile
- Jmeter/ResourceServer.jmx
- docker-compose.yml
- Removed threshold evaluation of performance tests to fail CI builds.
- Minor fixes and refactored code.
- Re-enabled SSL for Performance and Integration tests.
> Jenkins CI improvements

- README.md
Deployed NGINX in front of the jenkins server and enabled https. 
Updated git badge references to https://jenkins.iudx.io
> Updated git badge references

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/java/iudx/resource/server/databroker/SubscriptionService.java
- src/main/java/iudx/resource/server/databroker/util/Constants.java
> open resource id check for sub & ingestion

- docs/openapi.yaml
- src/main/java/iudx/resource/server/apiserver/AsyncRestApi.java
- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
- added async and metering API docs 
- improved data subscriber and data ingestion API response formats
> api docs improvements and additions

- Jenkinsfile
fix for stale test reports that might cause issue with PR builds.
> Jenkins CI update: Added cleanup of unit test reports after stage completion

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/AsyncRestApi.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/authorization/Api.java
- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
- src/main/java/iudx/resource/server/database/async/util/Util.java
- src/main/java/iudx/resource/server/database/elastic/ElasticClient.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V3.5.postman_collection.json
Changed paths to have `/ngsi-ld/v1`
Removed `user_id` from response of /async/status
> Fix: path for async

- pom.xml
Ref: https://github.com/datakaveri/iudx-aaa-server/pull/122
> Fix: logging dependencies for slf4j

- src/test/java/iudx/resource/server/databroker/AdapterEntitiesTest.java
Changed the configs for database from callback to postgres in AdapterEntitiesTest
> Fix: databroker configs

- src/main/java/iudx/resource/server/databroker/util/Constants.java
- src/main/resources/db/migration/V1_1__init-tables.sql
- flyway script tested
- changed **databroker** table name to **subscription_users**
- Appropriate changes in code for the changed table name.
> fixes/flyway [v3.5.0]

- Jenkinsfile
- flyway.conf
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/resources/db/migration/V2_1__alter-revoked-token-column.sql
- fix for revoke token date parse exception
> [fix] for date parse issue

- docs/openapi.yaml
- Duplicate for #235 for 3.5.0 branch
> async API docs

- src/main/java/iudx/resource/server/apiserver/subscription/SubscriptionService.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- Subscription flow mofication to select before every update.
> sub fetch records before update.

- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
duplicate of #241 for 3.5.0 branch
> metering bug

- pom.xml
- src/main/java/iudx/resource/server/cache/CacheVerticle.java
- src/main/java/iudx/resource/server/database/postgres/PostgresVerticle.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs (v3.5.0).postman_collection.json
- src/test/resources/rs.iudx.io.postman_environment.json
- correct audit, mgmt reset api in postman
- Adding stop method in postgres and cache verticle
- Remove redundant  old pkg  version of 'elasticsearch-rest-client'
- Adding 'between' timerel in audit temporal query.
> Miscellaneous bugs-fix

- pom.xml
- src/main/java/iudx/resource/server/cache/CacheVerticle.java
- src/main/java/iudx/resource/server/database/postgres/PostgresVerticle.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs (v3.5.0).postman_collection.json
- src/test/resources/rs.iudx.io.postman_environment.json
Duplicate of https://github.com/datakaveri/iudx-resource-server/pull/244 for v3.5.0 branch
> v3.5.0: Miscellaneous bugs-fix 

- src/main/java/iudx/resource/server/database/async/AsyncFileScrollProgressListener.java
- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
- src/main/java/iudx/resource/server/database/async/ProgressListener.java
- src/main/java/iudx/resource/server/database/async/util/S3FileOpsHelper.java
- src/main/java/iudx/resource/server/database/elastic/ElasticClient.java
- src/main/java/iudx/resource/server/database/postgres/PostgresVerticle.java
- src/test/java/iudx/resource/server/database/async/AsyncServiceTest.java
> async API progress issue fixed.

- src/main/java/iudx/resource/server/database/async/AsyncFileScrollProgressListener.java
- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
- src/main/java/iudx/resource/server/database/async/ProgressListener.java
- src/main/java/iudx/resource/server/database/elastic/ElasticClient.java
- src/main/java/iudx/resource/server/database/postgres/PostgresVerticle.java
- src/test/java/iudx/resource/server/database/async/AsyncServiceTest.java
Duplicate for PR #246 for branch 3.5.0
> async bug resolved

- pom.xml
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/handlers/ValidationHandler.java
- src/test/java/iudx/resource/server/apiserver/handlers/AuthHandlerTest.java
- src/test/java/iudx/resource/server/apiserver/handlers/FailureHandlerTest.java
- src/test/java/iudx/resource/server/apiserver/handlers/ValidationHandlerTest.java
Created test cases for apiserver/handlers
> Add handlers test cases

- Jenkins/resources/example-config.json
- Jenkins/resources/get-token.py
- Jenkinsfile
- Added python script to fetch tokens for the requested resources.
- The fetched tokens are then set as env variables on Jenkins and passed to the Jmeter script.
> Jenkins CI: Updated to fetch tokens from script for Jmeter tests

- src/test/java/iudx/resource/server/database/async/AsyncServiceTest.java
Commented a test because of the build failure: [Link](https://jenkins.iudx.io/job/iudx%20RS%20(master)%20pipeline/lastBuild/)
> Change AsyncServiceTest

- src/test/java/iudx/resource/server/apiserver/validation/DateTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/DistanceTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/GeoPropertyTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/GeoRelTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/GeometryTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/OptionsHeaderValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/OptionsTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/PaginationLimitTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/PaginationOffsetTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/QTypeValidatorTest.java
- src/test/java/iudx/resource/server/apiserver/validation/StringTypeValidatorTest.java
New classes added :-
OptionsHeaderValidatorTest
StringTypeValidatorTest
Changes made in:
geoPropetytypevaldator
PaginationOffsetTypeValidatorTest
qtypevalidator
distancetypevalidator
PaginationLimitTypeValidator
geoRelTypeValidator
optionsTypeValidator
geometryTypeValidator
DateTypeValidator-
> add-validator-types-test-cases

- src/main/java/iudx/resource/server/database/latest/RedisClient.java
Redis connection reset issue  : 
- Solved by periodically sending a ping command to Redis server (30s) [tested and working]. tcpKeepAlive option is by default set to true in vertx-redis-client.
> redis timeout issue.

- Jenkinsfile
- Added auto-deployment to docker-swarm.
- Image publication to ghcr and deployment to docker-swarm will only happen when changes in source code and related files are detected. (or if the build is triggered manually.)
- Runs integration tests against the updated server.
- Refactored performance test stage code.
> Jenkins CD: Added continuous deployment to Docker Swarm

- src/test/java/iudx/resource/server/databroker/DataBrokerServiceImplTest.java
Included test cases in [DataBrokerServiceImplTest](https://github.com/datakaveri/iudx-resource-server/commit/34f376eeb653a5e399add97cecfbe9c9a7cd2142)
> Add test cases in DataBrokerServiceImplTest

- src/main/java/iudx/resource/server/apiserver/query/NGSILDQueryParams.java
- src/test/java/iudx/resource/server/apiserver/query/NGSILDQueryParamsTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceImplTest.java
Created test cases [NGSILDQueryParamsTest](https://github.com/datakaveri/iudx-resource-server/pull/276/commits/39e3e95c62bb2e80cd6bcf07f08d339c285d85c5) for the class : [NGSILDQueryParams](https://github.com/datakaveri/iudx-resource-server/pull/276/commits/eeced1603411a516c387ff087e8c17578e10983d)
> Add apiserver query test cases

- pom.xml
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/database/latest/LatestDataServiceImpl.java
- Updated postgressql version 42.3.3 -> 42.4.0
- included SCRAM256 lib for postgres.
- update flyway version 7.11.1 -> 8.5..13
> pg_migratiopn changes

- SETUP.md
- configs/config-depl.json
- configs/config-dev.json
- configs/config-example.json
- configs/config-test.json
- src/main/java/iudx/resource/server/authenticator/Constants.java
- removal of  'resourceServerId',  'rsAdmin' as
grep -rnw src/ -e 'resourceServerId',
grep -rnw src/ -e 'rsAdmin' yields no result
- removal of 'serverMode' in constants as its not used anywhere
and subsequently the config option.
> Removal of unused config options in RS

- src/main/java/iudx/resource/server/databroker/listeners/AsyncQueryListener.java
- src/main/java/iudx/resource/server/databroker/listeners/RevokeClientQListener.java
- src/main/java/iudx/resource/server/databroker/listeners/UniqueAttribQListener.java
- src/test/java/iudx/resource/server/databroker/listeners/TestAsyncQueryListener.java
- src/test/java/iudx/resource/server/databroker/listeners/TestRevokeClientQListener.java
- src/test/java/iudx/resource/server/databroker/listeners/TestUniqueAttribQListener.java
- Bug resolved [stopped listening due to junit changes]
> listeners bug resolved 

- src/main/java/iudx/resource/server/database/async/util/S3FileOpsHelper.java
- more error logs to debug current s3 issues.
> error logs to debug s3 issue

- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/handlers/ValidationHandler.java
- src/test/java/iudx/resource/server/apiserver/handlers/AuthHandlerTest.java
- src/test/java/iudx/resource/server/apiserver/handlers/ValidationHandlerTest.java
Duplicate of PR #321 for the 4.0.0 branch
> post api bug

- docs/openapi.yaml
- corrected Async API endpoint
- Corrected endpoint in metering API params
> API docs changes

- Jmeter/ResourceServer.jmx
Fixing Jmeter JMX script for all issues in CI.
> Fix jmx script

- Jenkinsfile
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.environment.json
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.postman_collection.json
- Updated postman collection to contain all RS APIs
- Updated postman env file
> Postman Collection Update

- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/database/elastic/ElasticClient.java
- Allow open token holders to create subscriptions
> Open subscriptions API

- docs/openapi.yaml
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/management/ManagementApi.java
- src/main/java/iudx/resource/server/apiserver/management/ManagementApiImpl.java
- src/main/java/iudx/resource/server/apiserver/subscription/SubscriptionService.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/databroker/DataBrokerService.java
- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/main/java/iudx/resource/server/databroker/RabbitWebClient.java
- src/test/java/iudx/resource/server/apiserver/management/ManagementApiImplTest.java
- src/test/java/iudx/resource/server/apiserver/subscription/SubscriptionServiceTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceTest.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.postman_collection.json
- SRS 4.5.0 (1.11)
- Extension of /ingestion and /subscription end points
- Added postman collections
- Added Junit Testcases
> extension of ingestion and subscription end points

- Jenkinsfile
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/apiserver/util/RequestType.java
- src/main/java/iudx/resource/server/apiserver/validation/ValidatorsHandlersFactory.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/authorization/ConsumerAuthStrategy.java
- src/main/java/iudx/resource/server/common/Api.java
- src/main/java/iudx/resource/server/metering/MeteringService.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/main/java/iudx/resource/server/metering/util/QueryBuilder.java
- src/test/java/iudx/resource/server/metering/MeteringServiceTest.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.environment.json
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.postman_collection.json
- End point (/overview)
- Junit test case
- Postman updated
- Admin Token added in Postman Env
> /overview endpoints with testcase

- src/main/resources/db/migration/V4_3__auditingrs-add-column.sql
- Added new column in auditing_rs with time stamp without time zone
> Added new column in auditing_rs

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/authorization/ConsumerAuthStrategy.java
- src/main/java/iudx/resource/server/cache/cacheImpl/CatalogueCacheImpl.java
- src/main/java/iudx/resource/server/common/Api.java
- src/main/java/iudx/resource/server/metering/MeteringService.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/main/java/iudx/resource/server/metering/util/QueryBuilder.java
- src/test/java/iudx/resource/server/metering/MeteringServiceTest.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.postman_collection.json
- /summary end point
- Junit for /summary and insert query  in rmq
- Postman for /summary
> /summary api

- src/main/resources/db/migration/V4_4__Alter_subscriptions-table-add-columns.sql
> correct script for subscriptions schema

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/subscription/SubscriptionService.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/databroker/DataBrokerService.java
- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/main/java/iudx/resource/server/databroker/RabbitClient.java
- src/test/java/iudx/resource/server/apiserver/subscription/SubscriptionServiceTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceTest.java
* Code refector  for POST  /subscription and GET /subscription(for get all subscriptions)
> subscription api extention

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/main/java/iudx/resource/server/metering/util/QueryBuilder.java
- src/test/java/iudx/resource/server/metering/MeteringServiceTest.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V4.0.postman_collection.json
- added startime and endtime in summary api
- junit
- postman updated
> introduced st and et in summary endpoint

- src/main/java/iudx/resource/server/database/elastic/ElasticClient.java
* fixed Data alternate rows is missing a comma in Async api
> missing a comma

- docs/apidoc.html
- Updated API docs spec-url to work with nginx cos changes.
> [4.5.0] Updated apidoc.html spec-url

- src/main/resources/db/migration/V5_2__create-auditing-acl-apd-table.sql
* table create for audit acl-apd sever data.
> acl-apd auditing table

- src/main/resources/db/migration/V5_3__alter-auditing_rs-table-add-columns.sql
> alter auditing_rs

- src/main/java/iudx/resource/server/apiserver/AdminRestApi.java
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
> update auditing message [include resource group and itemtype]

- pom.xml
- src/main/java/iudx/resource/server/apiserver/AdminRestApi.java
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/AsyncRestApi.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
- src/main/java/iudx/resource/server/authenticator/JwtAuthenticationServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/model/JwtData.java
- src/main/java/iudx/resource/server/database/async/AsyncService.java
- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
- src/main/java/iudx/resource/server/databroker/listeners/AsyncQueryListener.java
- src/main/java/iudx/resource/server/metering/util/Constants.java
- src/main/resources/db/migration/V5_4__alter-auditing_rs-table-add-columns.sql
- src/test/java/iudx/resource/server/database/archives/DatabaseServiceTest.java
- src/test/java/iudx/resource/server/database/async/AsyncServiceTest.java
- src/test/java/iudx/resource/server/databroker/listeners/TestAsyncQueryListener.java
- added sql script for delegator_id
- changes done according to new column in auditing
- Junit updated
- PMD and Checkstyle solved
> drl column addition for auditing_rs table

- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V5.0.0.environment.json
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V5.0.0.postman_collection.json
Modifications and refactoring to include IUDX5.0 release changes
-  removal of resource group tokens
> Removal of resource group token and its uses in postman collection

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
Resolved Issue with response encoding in API verticle for Subscription API
> subscription API response issue

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/subscription/SubscriptionService.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/main/resources/db/migration/V5_5__alter-subscriptions-table-add-columns.sql
- src/test/java/iudx/resource/server/apiserver/subscription/SubscriptionServiceTest.java
- extend append subscription query
- modified subscriptions audit flow
> modify append subscription & subscription auditing flow

- src/main/resources/db/migration/V5_6__create_table_auditing_consent_log.sql
- Table for auditing consent log
> auditing consent log

- src/main/java/iudx/resource/server/apiserver/subscription/SubscriptionService.java
- Document Updation for Append Subscriptions
From,
```
{
"entities": [
"83c2e5c2-3574-4e11-9530-2b1fbdfce832"
]
}
```
To
```
{
"type": "urn:dx:rs:success",
"title": "success",
"results": {
"entities": [
"83c2e5c2-3574-4e11-9530-2b1fbdfce832"
]
}
}
```
> Change in docs of Append subs

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/subscription/SubscriptionService.java
- src/main/java/iudx/resource/server/apiserver/util/Constants.java
- src/test/java/iudx/resource/server/apiserver/subscription/SubscriptionServiceTest.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V5.0.0.postman_collection.json
- 2nd commit is for response change for append subs according to docs
> SDM_code_change

- docs/openapi.yaml
- src/test/java/iudx/resource/server/apiserver/integrationTests/adaptergrouplevelapis/AdapterGroupLevelAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/asyncsearchapis/AsyncSearchAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/complexcountapis/ComplexCountAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/complexsearchapis/ComplexSearchAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/consumerauditapis/ConsumerAuditAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/filterapis/GetAttributeWithFilterIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/filterapis/GetBetweenTemporalAttributeWithFilterIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/subscriptionapis/StreamingSubscriptionAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/summaryapis/SummaryAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/temporalcountapis/GetAfterTemporalCountIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/temporalcountapis/GetBeforeTemporalCountIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/temporalcountapis/GetBetweenTemporalCountIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/temporalsearchapis/GetAfterTemporalEntitiesIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/temporalsearchapis/GetBeforeTemporalEntitiesIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/temporalsearchapis/GetBetweenTemporalEntitiesIT.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/validations/validationAPIsIT.java
#462 Same code was written in this PR
> Rest Assured Tests for Resource Server

- src/main/resources/db/migration/V5_10__create_table_cat_summary.sql
- src/main/resources/db/migration/V5_9__add-indexes-for-auditing-tables.sql
- Added index on time column to improve query time
> Alterschema

- docs/openapi.yaml
> doc verion updated

- src/main/resources/db/migration/V5_12__Alter-dmp-audit-table.sql
- src/main/resources/db/migration/V5_7__create_audit_table_for_dmp.sql
Changed the data type of the primary key constraint in auditing dmp table
> Update audit schema

- scripts/subscription-monitoring-config.json
- scripts/subscription-monitoring-migration.py
Script to migrate exchanges from postgres db and create exchange and queue binding in rabbitmq
> subscription-monitoring migration script

- docs/openapi.yaml
- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/resetPasswordAPI/ResetPasswordAPIsIT.java
- src/test/java/iudx/resource/server/databroker/DBServiceImplTest.java
- src/test/resources/IUDX-Resource-Server-Consumer-APIs-V5.5.0.postman_collection.json
Corrected pr #510 , according to requirement
> refractor response

- src/main/resources/db/migration/V5_13__Alter-rs-table.sql
- Added primary key in postgres for auditing rs table
> added primary key in postgres

- .github/workflows/docker-tag-stable.yml
- .github/workflows/docker-tag.yml
- Jenkinsfile
Separated docker tag workflow file to master and stable branch
https://github.com/datakaveri/iudx-deployment/issues/721
> Separated docker tag workflow file

- src/main/java/iudx/resource/server/authenticator/AuthenticationVerticle.java
- src/main/java/iudx/resource/server/authenticator/Constants.java
JWT Leeway time Added in Authentication Verticle
> jwt leeway time added

- src/main/java/iudx/resource/server/database/elastic/ElasticClient.java
- src/main/java/iudx/resource/server/database/elastic/EsResponseFormatter.java
- src/main/java/iudx/resource/server/database/elastic/EsResponseFormatterToCsv.java
- src/main/java/iudx/resource/server/database/elastic/EsResponseFormatterToJson.java
- src/main/java/iudx/resource/server/database/elastic/EsResponseFormatterToParquet.java
- src/main/java/iudx/resource/server/database/elastic/JsonFlatten.java
- src/test/java/iudx/resource/server/database/elastic/TestEsResponseFormatterToCsv.java
> async csv file

- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/database/elastic/EsResponseFormatterToJson.java
- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/main/java/iudx/resource/server/databroker/DataBrokerVerticle.java
- src/test/java/iudx/resource/server/databroker/AdapterEntitiesTest.java
- src/test/java/iudx/resource/server/databroker/DBServiceImplTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceImplTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceTest.java
- RMQ message fix for adaptor entity api
> publish adaptor , rmq push message change

- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
> added logger

- docs/openapi.yaml
- src/main/java/iudx/resource/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/resource/server/apiserver/handlers/AuthHandler.java
- src/main/java/iudx/resource/server/apiserver/management/ManagementApi.java
- src/main/java/iudx/resource/server/apiserver/management/ManagementApiImpl.java
- src/main/java/iudx/resource/server/databroker/DataBrokerService.java
- src/main/java/iudx/resource/server/databroker/DataBrokerServiceImpl.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/adaptorResourceLevel/AdaptorResourceLevelAPIsIT.java
- src/test/java/iudx/resource/server/apiserver/management/ManagementApiImplTest.java
- src/test/java/iudx/resource/server/databroker/DBServiceImplTest.java
- src/test/java/iudx/resource/server/databroker/DataBrokerServiceTest.java
- src/test/resources/DX-Resource-Server-Consumer-APIs.postman_collection.json
> ingestion entities api for multiple data ingestion

- src/main/java/iudx/resource/server/apiserver/query/QueryMapper.java
- src/main/java/iudx/resource/server/metering/MeteringServiceImpl.java
- src/test/java/iudx/resource/server/apiserver/integrationTests/summaryapis/SummaryAPIsIT.java
- src/test/java/iudx/resource/server/metering/MeteringServiceTest.java
> improved loggers

- src/main/java/iudx/resource/server/apiserver/metering/MeteringVerticle.java
- src/main/java/iudx/resource/server/apiserver/metering/handler/MeteringHandler.java
- src/main/java/iudx/resource/server/apiserver/metering/model/MeteringLog.java
- src/main/java/iudx/resource/server/apiserver/metering/model/package-info.java
- src/main/java/iudx/resource/server/apiserver/metering/service/MeteringService.java
- src/main/java/iudx/resource/server/apiserver/metering/service/MeteringServiceImpl.java
- src/main/java/iudx/resource/server/apiserver/metering/service/package-info.java
- src/main/java/iudx/resource/server/apiserver/metering/util/Constant.java
- src/main/java/iudx/resource/server/apiserver/subscription/controller/SubscriptionController.java
- src/main/java/iudx/resource/server/apiserver/subscription/model/GetResultModel.java
- src/main/java/iudx/resource/server/apiserver/subscription/model/PostModelSubscription.java
- src/main/java/iudx/resource/server/apiserver/subscription/service/SubscriptionService.java
- src/main/java/iudx/resource/server/apiserver/subscription/service/SubscriptionServiceImpl.java
- src/main/java/iudx/resource/server/authenticator/handler/authentication/AuthHandler.java
- src/main/java/iudx/resource/server/cache/service/type/RevokedClientCache.java
- src/main/java/iudx/resource/server/cache/service/type/UniqueAttributeCache.java
- src/main/java/iudx/resource/server/common/Constants.java
- src/main/java/iudx/resource/server/common/ResultInfo.java
- src/main/java/iudx/resource/server/common/RoutingContextHelper.java
- src/main/java/iudx/resource/server/databroker/DataBrokerVerticle.java
- src/main/java/iudx/resource/server/databroker/service/DataBrokerService.java
- src/main/java/iudx/resource/server/databroker/service/DataBrokerServiceImpl.java
- src/main/java/iudx/resource/server/databroker/util/RabbitClient.java
- src/main/java/iudx/resource/server/databroker/util/Util.java
- src/test/java/iudx/resource/server/apiserver/subscription/SubscriptionServiceServiceTest.java
> subscription code

- src/main/java/iudx/resource/server/apiserver/usermanagement/controller/UserManagementController.java
> user management

- src/main/java/org/cdpg/dx/common/ErrorCode.java
- src/main/java/org/cdpg/dx/common/ErrorCodeMapping.md
- src/main/java/org/cdpg/dx/database/postgres/PostgresVerticle.java
- src/main/java/org/cdpg/dx/database/postgres/exceptions/InvalidQueryException.java
- src/main/java/org/cdpg/dx/database/postgres/models/Condition.java
- src/main/java/org/cdpg/dx/database/postgres/models/ConditionComponent.java
- src/main/java/org/cdpg/dx/database/postgres/models/ConditionGroup.java
- src/main/java/org/cdpg/dx/database/postgres/models/DeleteQuery.java
- src/main/java/org/cdpg/dx/database/postgres/models/InsertQuery.java
- src/main/java/org/cdpg/dx/database/postgres/models/OrderBy.java
- src/main/java/org/cdpg/dx/database/postgres/models/Query.java
- src/main/java/org/cdpg/dx/database/postgres/models/QueryResult.java
- src/main/java/org/cdpg/dx/database/postgres/models/SelectQuery.java
- src/main/java/org/cdpg/dx/database/postgres/models/UpdateQuery.java
- src/main/java/org/cdpg/dx/database/postgres/service/PostgresService.java
- src/main/java/org/cdpg/dx/database/postgres/service/PostgresServiceImpl.java
- src/main/java/org/cdpg/dx/databroker/client/RabbitClient.java
- src/main/java/org/cdpg/dx/databroker/service/DataBrokerService.java
- src/main/java/org/cdpg/dx/databroker/service/DataBrokerServiceImpl.java
> databroker,postgres and other common classes

- src/main/java/iudx/resource/server/apiserver/auditing/handler/AuditingHandler.java
- src/main/java/org/cdpg/dx/auditing/handler/AuditingHandler.java
- src/main/java/org/cdpg/dx/auditing/service/AuditLog.java
- src/main/java/org/cdpg/dx/auditing/service/RsAuditLogData.java
- src/main/java/org/cdpg/dx/auditing/util/Constants.java
- src/main/java/org/cdpg/dx/common/ErrorCode.java
- src/main/java/org/cdpg/dx/common/ErrorCodeMapping.md
- src/main/java/org/cdpg/dx/common/models/DxRole.java
- src/main/java/org/cdpg/dx/common/models/JwtData.java
- src/main/java/org/cdpg/dx/common/models/User.java
- src/main/java/org/cdpg/dx/database/postgres/PostgresVerticle.java
- src/main/java/org/cdpg/dx/database/postgres/exceptions/InvalidQueryException.java
- src/main/java/org/cdpg/dx/database/postgres/models/Condition.java
- src/main/java/org/cdpg/dx/database/postgres/models/ConditionComponent.java
- src/main/java/org/cdpg/dx/database/postgres/models/ConditionGroup.java
- src/main/java/org/cdpg/dx/database/postgres/models/DeleteQuery.java
- src/main/java/org/cdpg/dx/database/postgres/models/InsertQuery.java
- src/main/java/org/cdpg/dx/database/postgres/models/OrderBy.java
- src/main/java/org/cdpg/dx/database/postgres/models/Query.java
- src/main/java/org/cdpg/dx/database/postgres/models/QueryResult.java
- src/main/java/org/cdpg/dx/database/postgres/models/SelectQuery.java
- src/main/java/org/cdpg/dx/database/postgres/models/UpdateQuery.java
- src/main/java/org/cdpg/dx/database/postgres/service/PostgresService.java
- src/main/java/org/cdpg/dx/database/postgres/service/PostgresServiceImpl.java
- src/main/java/org/cdpg/dx/databroker/client/RabbitClient.java
- src/main/java/org/cdpg/dx/databroker/service/DataBrokerService.java
- src/main/java/org/cdpg/dx/databroker/service/DataBrokerServiceImpl.java
- src/main/java/org/cdpg/dx/util/RoutingContextHelper.java
Added auditing module in org.cdpg.dx package.
> added audting module

- src/main/java/org/cdpg/dx/rs/usermanagement/service/UserManagementService.java
- src/main/java/org/cdpg/dx/rs/usermanagement/service/UserManagementServiceImpl.java
- UsermanagementServiceImpl with new code structure.
> user management impl

- src/main/java/org/cdpg/dx/rs/admin/service/AdminService.java
- src/main/java/org/cdpg/dx/rs/admin/service/AdminServiceImpl.java
- src/main/java/org/cdpg/dx/rs/admin/util/BroadcastEventType.java
- src/main/java/org/cdpg/dx/rs/admin/util/Constants.java
- Admin Service Impl using new code structure and postgres model
- Need to revisit code once postgres model is updated
> admin service impl

- src/main/java/org/cdpg/dx/common/ErrorCode.java
- src/main/java/org/cdpg/dx/common/ErrorCodeMapping.md
- src/main/java/org/cdpg/dx/common/ErrorMessage.java
- src/main/java/org/cdpg/dx/revoked/RevokedVerticle.java
- src/main/java/org/cdpg/dx/revoked/client/RevokedClient.java
- src/main/java/org/cdpg/dx/revoked/client/RevokedClientImpl.java
- src/main/java/org/cdpg/dx/revoked/handler/TokenRevokedHandler.java
- src/main/java/org/cdpg/dx/revoked/service/RevokedService.java
- src/main/java/org/cdpg/dx/revoked/service/RevokedServiceImpl.java
- Created Revoked Handler
- Moved Revoked Cache in new structure.
> revoked handler and impl

- src/main/java/org/cdpg/dx/util/HttpStatusCode.java
- src/main/java/org/cdpg/dx/util/ResponseUrn.java
- src/main/java/org/cdpg/dx/util/RoutingContextHelper.java
- src/main/java/org/cdpg/dx/validations/idhandler/GetIdForIngestionEntityHandler.java
- src/main/java/org/cdpg/dx/validations/idhandler/GetIdFromBodyHandler.java
- src/main/java/org/cdpg/dx/validations/idhandler/GetIdFromParams.java
- src/main/java/org/cdpg/dx/validations/idhandler/GetIdFromPathHandler.java
- src/main/java/org/cdpg/dx/validations/util/Constants.java
- get id from :
- path
- param
- body
- ingestionentity(special case)
> added Id request handlers

- src/main/java/org/cdpg/dx/database/postgres/PostgresVerticle.java
- src/main/java/org/cdpg/dx/database/postgres/models/InsertQuery.java
- src/main/java/org/cdpg/dx/database/postgres/service/PostgresServiceImpl.java
- src/main/java/org/cdpg/dx/rs/subscription/model/GetSubscriptionModel.java
- src/main/java/org/cdpg/dx/rs/subscription/model/PostSubscriptionModel.java
- src/main/java/org/cdpg/dx/rs/subscription/model/SubscriberDetails.java
- src/main/java/org/cdpg/dx/rs/subscription/model/SubscriptionMetaData.java
- src/main/java/org/cdpg/dx/rs/subscription/model/package-info.java
- src/main/java/org/cdpg/dx/rs/subscription/service/SubscriptionService.java
- src/main/java/org/cdpg/dx/rs/subscription/service/SubscriptionServiceImpl.java
- src/main/java/org/cdpg/dx/rs/subscription/service/package-info.java
- src/main/java/org/cdpg/dx/rs/subscription/util/Constants.java
- src/main/java/org/cdpg/dx/rs/subscription/util/SubsType.java
- Added subscription code
- Remote unnecessary logger from pg
> subscription added

- pom.xml
- src/main/java/org/cdpg/dx/databroker/DataBrokerVerticle.java
- src/main/java/org/cdpg/dx/databroker/client/RabbitWebClient.java
- src/test/java/org/cdpg/dx/databroker/client/RabbitClientTest.java
- src/test/java/org/cdpg/dx/databroker/service/DataBrokerServiceImplTest.java
> databroker

- pom.xml
- src/main/java/org/cdpg/dx/databroker/DataBrokerVerticle.java
- src/main/java/org/cdpg/dx/databroker/client/RabbitWebClient.java
- src/test/java/org/cdpg/dx/databroker/client/RabbitClientTest.java
- Pom changes to include RMQ test containers
- Rabbit Client test cases
> rmq test container and rabbitclient test cases

- src/main/java/org/cdpg/dx/rs/ingestion/model/AdapterMetaDataModel.java
- src/main/java/org/cdpg/dx/rs/ingestion/model/package-info.java
- src/main/java/org/cdpg/dx/rs/ingestion/service/IngestionService.java
- src/main/java/org/cdpg/dx/rs/ingestion/service/IngestionServiceImpl.java
- src/main/java/org/cdpg/dx/rs/ingestion/service/package-info.java
- src/main/java/org/cdpg/dx/rs/ingestion/util/Constants.java
- Ingestion service using new postgres
> ingestion subs

- src/test/java/org/cdpg/dx/rs/ingestion/service/IngestionServiceImplTest.java
- src/test/java/org/cdpg/dx/rs/subscription/service/SubscriptionServiceImplTest.java
- ingestion service test cases using containers
> ingestion service test using containers

- src/main/java/org/cdpg/dx/databroker/client/RabbitClient.java
- src/main/java/org/cdpg/dx/rs/admin/service/AdminService.java
- src/main/java/org/cdpg/dx/rs/admin/service/AdminServiceImpl.java
- src/main/java/org/cdpg/dx/rs/admin/service/package-info.java
- src/main/java/org/cdpg/dx/rs/admin/util/BroadcastEventType.java
- src/main/java/org/cdpg/dx/rs/admin/util/Constants.java
- src/main/java/org/cdpg/dx/rs/ingestion/service/package-info.java
- src/main/java/org/cdpg/dx/rs/subscription/service/package-info.java
- src/main/java/org/cdpg/dx/rs/usermanagement/service/UserManagementService.java
- src/main/java/org/cdpg/dx/rs/usermanagement/service/UserManagementServiceImpl.java
- src/main/java/org/cdpg/dx/rs/usermanagement/service/package-info.java
- src/test/java/org/cdpg/dx/rs/admin/service/AdminServiceImplTest.java
- src/test/java/org/cdpg/dx/rs/admin/service/a.java
- src/test/java/org/cdpg/dx/rs/usermanagement/service/UserManagementServiceImplTest.java
- Admin Service Impl
- User Management Service Impl
- Test cases of Admin Service and User Management Service using test container
> admin and usermanagement

- src/main/java/org/cdpg/dx/database/postgres/models/UpdateQuery.java
- src/main/java/org/cdpg/dx/database/postgres/service/PostgresServiceImpl.java
- Update Query to handle multiple conditions
- Postgres Service impl to handle time insertions
> Updated postgres

- src/main/java/org/cdpg/dx/common/util/EntityUtil.java
- src/main/java/org/cdpg/dx/database/postgres/base/dao/AbstractBaseDAO.java
- src/main/java/org/cdpg/dx/database/postgres/base/dao/BaseDAO.java
- src/main/java/org/cdpg/dx/database/postgres/base/enitty/BaseEntity.java
- src/main/java/org/cdpg/dx/rs/ingestion/dao/IngestionDAO.java
- src/main/java/org/cdpg/dx/rs/ingestion/dao/impl/IngestionDAOImpl.java
- src/main/java/org/cdpg/dx/rs/ingestion/model/IngestionDTO.java
- src/main/java/org/cdpg/dx/rs/ingestion/service/IngestionServiceImpl.java
- src/main/java/org/cdpg/dx/rs/ingestion/util/Constants.java
- src/test/java/org/cdpg/dx/rs/ingestion/service/IngestionServiceImplTest.java
- dao implementation of ingestion service
> ingestion dao

- docs/openapi.yaml
- src/main/java/org/cdpg/dx/rs/apiserver/ControllerFactory.java
- src/main/java/org/cdpg/dx/rs/search/controller/SearchController.java
- src/main/java/org/cdpg/dx/rs/usermanagement/controller/UserManagementController.java
Controller for reset Password added.
> resetPassword-Controller

- docs/openapi.yaml
- src/main/java/org/cdpg/dx/rs/admin/controller/AdminController.java
- src/main/java/org/cdpg/dx/rs/admin/service/AdminServiceImpl.java
- src/main/java/org/cdpg/dx/rs/apiserver/ControllerFactory.java
- src/main/java/org/cdpg/dx/util/Constants.java
contains commits regarding controller for admin apis
> admin-api-controller

- src/main/java/iudx/resource/server/database/async/AsyncServiceImpl.java
> logger updated

- Jenkinsfile
- docker-compose.test.yml
- docker/test.dockerfile
1.Added conditional statement(pipeline will run only when changes in source code,dependecies or manually triggered)
2.Add Vulnerability Scanning using Trivy.
> [Jenkins CI] [DI-20] optimized jenkinsfile
